on:
  workflow_call:
    inputs:
      GH_PULL_REQUEST_ID:
        type: integer

env:
  GH_PULL_REQUEST_ID: ${{ inputs.GH_PULL_REQUEST_ID }}

jobs:
  try-this-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.GH_PULL_REQUEST_ID-inp }}